In [1]:
import torch

# Create a simple tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("Tensor:")
print(x)
print(f"\nShape: {x.shape}")
print(f"Device: {x.device}")

Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Shape: torch.Size([2, 3])
Device: cpu


In [2]:
# Move tensor to M4's GPU
device = torch.device("mps")
x_gpu = x.to(device)

print(f"Tensor is now on: {x_gpu.device}")
print(x_gpu)

# Let's do some math on the GPU!
result = x_gpu * 2
print(f"\nMultiplied by 2:")
print(result)

Tensor is now on: mps:0
tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')

Multiplied by 2:
tensor([[ 2,  4,  6],
        [ 8, 10, 12]], device='mps:0')


In [3]:
import time

# Create a BIG tensor
size = 5000
big_tensor_cpu = torch.randn(size, size)  # Random numbers on CPU
big_tensor_gpu = big_tensor_cpu.to("mps")  # Move to GPU

# Time CPU computation
start = time.time()
result_cpu = big_tensor_cpu @ big_tensor_cpu  # Matrix multiplication
cpu_time = time.time() - start

# Time GPU computation
start = time.time()
result_gpu = big_tensor_gpu @ big_tensor_gpu  # Same operation on GPU
torch.mps.synchronize()  # Wait for GPU to finish
gpu_time = time.time() - start

print(f"CPU time: {cpu_time:.4f} seconds")
print(f"GPU time: {gpu_time:.4f} seconds")
print(f"GPU is {cpu_time/gpu_time:.1f}x faster! 🚀")

CPU time: 0.1847 seconds
GPU time: 0.2527 seconds
GPU is 0.7x faster! 🚀


In [4]:
# Let's go MUCH bigger
size = 1000000

big_tensor_cpu = torch.randn(size, size)
big_tensor_gpu = big_tensor_cpu.to("mps")

# Warmup GPU (important!)
_ = big_tensor_gpu @ big_tensor_gpu
torch.mps.synchronize()

# Now time it
start = time.time()
result_cpu = big_tensor_cpu @ big_tensor_cpu
cpu_time = time.time() - start

start = time.time()
result_gpu = big_tensor_gpu @ big_tensor_gpu
torch.mps.synchronize()
gpu_time = time.time() - start

print(f"Size: {size}x{size}")
print(f"CPU time: {cpu_time:.4f} seconds")
print(f"GPU time: {gpu_time:.4f} seconds")
print(f"Speedup: {cpu_time/gpu_time:.1f}x")

Size: 10000x10000
CPU time: 1.3987 seconds
GPU time: 1.1044 seconds
Speedup: 1.3x


In [ ]:
# Let's go MUCH bigger
size = 1000000

big_tensor_cpu = torch.randn(size, size)
big_tensor_gpu = big_tensor_cpu.to("mps")

# Warmup GPU (important!)
_ = big_tensor_gpu @ big_tensor_gpu
torch.mps.synchronize()

# Now time it
start = time.time()
result_cpu = big_tensor_cpu @ big_tensor_cpu
cpu_time = time.time() - start

start = time.time()
result_gpu = big_tensor_gpu @ big_tensor_gpu
torch.mps.synchronize()
gpu_time = time.time() - start

print(f"Size: {size}x{size}")
print(f"CPU time: {cpu_time:.4f} seconds")
print(f"GPU time: {gpu_time:.4f} seconds")
print(f"Speedup: {cpu_time/gpu_time:.1f}x")

In [3]:
import torch

guess = torch.tensor(3.0, requires_grad=True)
target = torch.tensor(5.0)

print(f"Starting guess : {guess.item()}")

learning_rate = 0.1

for step in range(10):
    loss = (guess-target) ** 2 #cal loss

    loss.backward() #calculate gradient 

Starting guess : 3.0


In [8]:
import torch

x= torch.tensor(2.0)
y_target= torch.tensor(10.0)

w= torch.tensor(1.0, requires_grad=True)
b= torch.tensor(1.0, requires_grad=True)

print(f"Initial weights: w={w.item()}, b={w.item()}")

y_pred = w * x + b  # (1.0 * 2.0) + 1.0 = 3.0
print(f"Prediction: {y_pred.item()}")

# 3. Calculate Loss (Mean Squared Error)
loss = (y_pred - y_target)**2  # (3.0 - 10.0)^2 = 49.0
print(f"Loss: {loss.item()}")

# 4. Backward Pass
# Before backward, gradients are None
print(f"Gradient of w before backward: {w.grad}")

loss.backward()

# 5. Inspect Gradients
# d(loss)/dw = 2 * (y_pred - y_target) * x = 2 * (-7) * 2 = -28
print(f"Gradient of w after backward: {w.grad.item()}")
print(f"Gradient of b after backward: {b.grad.item()}")

# 6. Gradient Accumulation Warning
# If we run backward again without zeroing, gradients will add up!
loss_new = (w * x + b - y_target)**2
loss_new.backward()
print(f"Gradient of w after second backward (accumulated): {w.grad.item()}")
Use code with caution.

Breakdown of the Syntax
requires_grad=True: This flag is essential. It tells PyTorch to build a computational graph for this tensor [5, 6]. Without this, backward() will not find any variables to update.
loss.backward(): This triggers the chain rule. It calculates the derivative of the loss with respect to every leaf node (like w and b) that has requires_grad=True [1, 10].
.grad: This is where the result is stored. Note that backward() doesn't return the gradient; it populates the .grad attribute of the original tensors [1, 3].
Gradient Accumulation: In the example above, you'll notice the second backward pass makes the gradient -56 instead of -28. This is why in a real training loop, you must use optimizer.zero_grad() or w.grad.zero_() before the next pass [8].
Visualizing the Training Loop
In a practical application (like a Neural Network), the syntax usually looks like this:
python
# Standard pattern in Jupyter cells
optimizer.zero_grad()   # 1. Reset gradients
output = model(input)    # 2. Forward pass
loss = criterion(output, target) # 3. Compute loss
loss.backward()          # 4. Backpropagate (compute grads)
optimizer.step()         # 5. Update weights
Use code with caution.

For more details on how the computational graph is handled, you can refer to the PyTorch Autograd Tutorial [2, 5].




Show me an example of retain_graph=True

Explain how gradients accumulate in detail

What are common optimizers in PyTorch?


SyntaxError: unterminated string literal (detected at line 39) (2810649762.py, line 39)

In [9]:
import torch

# 1. Setup: Create a simple linear model y = w*x + b
# We set requires_grad=True to tell PyTorch to track the gradients
x = torch.tensor([2.0])
y_target = torch.tensor([10.0])

w = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([1.0], requires_grad=True)

print(f"Initial weights: w={w.item()}, b={b.item()}")

# 2. Forward Pass: Predict y
y_pred = w * x + b  # (1.0 * 2.0) + 1.0 = 3.0
print(f"Prediction: {y_pred.item()}")

# 3. Calculate Loss (Mean Squared Error)
loss = (y_pred - y_target)**2  # (3.0 - 10.0)^2 = 49.0
print(f"Loss: {loss.item()}")

# 4. Backward Pass
# Before backward, gradients are None
print(f"Gradient of w before backward: {w.grad}")

loss.backward()

# 5. Inspect Gradients
# d(loss)/dw = 2 * (y_pred - y_target) * x = 2 * (-7) * 2 = -28
print(f"Gradient of w after backward: {w.grad.item()}")
print(f"Gradient of b after backward: {b.grad.item()}")

# 6. Gradient Accumulation Warning
# If we run backward again without zeroing, gradients will add up!
loss_new = (w * x + b - y_target)**2
loss_new.backward()
print(f"Gradient of w after second backward (accumulated): {w.grad.item()}")


Initial weights: w=1.0, b=1.0
Prediction: 3.0
Loss: 49.0
Gradient of w before backward: None
Gradient of w after backward: -28.0
Gradient of b after backward: -14.0
Gradient of w after second backward (accumulated): -56.0


In [25]:
import torch

# Starting guess
guess = torch.tensor(3.0, requires_grad=True)
target = torch.tensor(3.50)

print(f"Starting guess: {guess.item()}")

# Learning rate: how big of a step to take
learning_rate = 0.5

# Train for 10 steps
for step in range(10):
    # Calculate loss
    loss = (guess - target) ** 2
    
    # Calculate gradient
    loss.backward()

#Starting to u[pdate GUESs in opposite direction of gradient

    with torch.no_grad(): #dont track this itseems
        guess = guess - learning_rate * guess.grad
        guess.requires_grad = True #re-enable tracking


    guess.grad = None #Clear gradient for next iteration 
    print(f"Step {step+1} : Guess = {guess.item():.4f}, Loss={loss.item():.4f}")


Starting guess: 3.0
Step 1 : Guess = 3.5000, Loss=0.2500
Step 2 : Guess = 3.5000, Loss=0.0000
Step 3 : Guess = 3.5000, Loss=0.0000
Step 4 : Guess = 3.5000, Loss=0.0000
Step 5 : Guess = 3.5000, Loss=0.0000
Step 6 : Guess = 3.5000, Loss=0.0000
Step 7 : Guess = 3.5000, Loss=0.0000
Step 8 : Guess = 3.5000, Loss=0.0000
Step 9 : Guess = 3.5000, Loss=0.0000
Step 10 : Guess = 3.5000, Loss=0.0000


In [26]:
import torch

# Try different learning rates
learning_rates = [0.01, 0.1, 0.5, 0.9]

for lr in learning_rates:
    guess = torch.tensor(3.0, requires_grad=True)
    target = torch.tensor(5.0)
    
    print(f"\n--- Learning Rate = {lr} ---")
    
    for step in range(10):
        loss = (guess - target) ** 2
        loss.backward()
        
        with torch.no_grad():
            guess = guess - lr * guess.grad
            guess.requires_grad = True
        
        guess.grad = None
        
        if step < 3 or step == 9:  # Print first 3 and last step
            print(f"Step {step+1}: Guess = {guess.item():.4f}, Loss = {loss.item():.4f}")
        elif step == 3:
            print("...")
    
    print(f"Final: {guess.item():.4f}")


--- Learning Rate = 0.01 ---
Step 1: Guess = 3.0400, Loss = 4.0000
Step 2: Guess = 3.0792, Loss = 3.8416
Step 3: Guess = 3.1176, Loss = 3.6895
...
Step 10: Guess = 3.3659, Loss = 2.7805
Final: 3.3659

--- Learning Rate = 0.1 ---
Step 1: Guess = 3.4000, Loss = 4.0000
Step 2: Guess = 3.7200, Loss = 2.5600
Step 3: Guess = 3.9760, Loss = 1.6384
...
Step 10: Guess = 4.7853, Loss = 0.0721
Final: 4.7853

--- Learning Rate = 0.5 ---
Step 1: Guess = 5.0000, Loss = 4.0000
Step 2: Guess = 5.0000, Loss = 0.0000
Step 3: Guess = 5.0000, Loss = 0.0000
...
Step 10: Guess = 5.0000, Loss = 0.0000
Final: 5.0000

--- Learning Rate = 0.9 ---
Step 1: Guess = 6.6000, Loss = 4.0000
Step 2: Guess = 3.7200, Loss = 2.5600
Step 3: Guess = 6.0240, Loss = 1.6384
...
Step 10: Guess = 4.7853, Loss = 0.0721
Final: 4.7853


In [27]:
import torch
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("M4 GPU is ready!")
else:
    device = torch.device("cpu")
    print("Falling back to CPU.")

# Move your model or data to the GPU
# model.to(device)


M4 GPU is ready!
